### ISSUE TITLE
`<note>` appears before where the note should be, instead of after

### ISSUE THREAD

**Issue by earboxer** [openbibleinfo/American-Standard-Version-Bible#4]
e.g. Genesis 1:1

```xml
and the Spirit of God <note caller="-" style="f"><char style="ft">Or, <char style="it">was brooding upon</char></char></note>moved upon the face of the waters.
```

It seems like the note should be placed placed after the referent, so that it can be rendered like

> and the Spirit of God moved upon [Or, *was brooding upon*] the face of the waters.

(but usx is kind of disappointing in that notes sit in place in the text, instead of referring to a block of text...)

**Comment by openbibleinfo** [comment]
Hello, this would make sense, but the ASV puts footnotes before the text they reference. The NASB carries forward this approach. https://www.biblegateway.com/passage/?search=Gen1&version=NASB,ASV
